----DELETE TABLE STATS----
exec dbms_stats.delete_table_stats(user, 'Track');
exec dbms_stats.delete_table_stats(user, 'Station');
exec dbms_stats.delete_table_stats(user, 'TrainRecipe');
exec dbms_stats.delete_table_stats(user, 'Train');
exec dbms_stats.delete_table_stats(user, 'Place');
exec dbms_stats.delete_table_stats(user, 'Carriage');
exec dbms_stats.delete_table_stats(user, 'Locomotive');
exec dbms_stats.delete_table_stats(user, 'Car');
exec dbms_stats.delete_table_stats(user, 'License');
exec dbms_stats.delete_table_stats(user, 'CargoType');